version: '3'

services:
  manga-app:
    build: .
    command: "sh -c 'yarn && yarn prisma db push && yarn start:dev'"
    ports:
      - 3333:3333
      - 5555:5555
    volumes:
      - .:/home/node/manga-app
    depends_on:
      - manga-db
    env_file:
      - .env

  manga-db:
    container_name: manga-db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env

  manga-front:
    build: ./frontend
    command: "sh -c 'yarn && yarn dev'"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/manga-app
    depends_on:
      - manga-app
